### ISSUE TITLE
Any ideas on how to unit test the result?

### ISSUE THREAD

**Issue by zwcloud** [Bl4ckb0ne/delaunay-triangulation#15]
For example, a test case from: [delaunay-triangulation/tests/tests.cpp](https://github.com/Bl4ckb0ne/delaunay-triangulation/blob/master/tests/tests.cpp):

```cpp
TEST_CASE("Delaunay triangulation should be able to handle 10000 points as float", "[DelaunayTest]") {
    std::vector<Vector2<float> > points(1e4);
    srand(666);
    for (size_t i=0; i < 1e4; ++i)
    {
        float x = (float)rand() / (float)RAND_MAX;
        float y = (double)rand() / (float)RAND_MAX;
        points.at(i) = Vector2<float>(x, y);
    }
    REQUIRE(10000 == points.size());
    Delaunay<float> triangulation;
    const std::vector<Triangle<float> > triangles = triangulation.triangulate(points);
}
```

Why not test the result, including `const std::vector<Triangle<float> > triangles`? The test case only guarantees that there is no run-time error but not the correctness of the triangulation result.

**Comment by Bl4ckb0ne** [comment]
With a sample of data of that size, it would be hard and complex to test it properly. This is more of a "performance" test, to see if the implementation can process 1000 points without crashing or going out of memory.

Accuracy test against data from other implementations could be useful, but it would require a lot of time to setup.
