### ISSUE TITLE
Missing include

### ISSUE THREAD

**Issue by Epono** [Bl4ckb0ne/delaunay-triangulation#2]
Hi,

Very nice work, I had to implement it recently for a school project and I have to say yours is way cleaner ^^

But I think there is a little bug, when I created a Visual Studio 2015 project, after I added SFML, I still had one error with std::array, and adding `#include <array>` on top of main.cpp fixed it.

**Comment by Bl4ckb0ne** [comment]
That's strage, it works on my computer, with and without it.
I added it, thanks.
