### ISSUE TITLE
Allow using float instead of double

### ISSUE THREAD

**Issue by ubruhin** [Bl4ckb0ne/delaunay-triangulation#27]
Hi,

I use an older version of this library in my project [LibrePCB](https://librepcb.org) and I was able to use `qreal` as template argument. The typedef `qreal` is provided by Qt and usually equals to `double`, but for embedded targets with only a single-precision FPU it might equal to `float` for performance reasons. This is very handy for application developers since we don't have to care much about this topic, just always use `qreal` for floating point operations and it should be working fine.

But now I'd like to update to the latest version of this library and realized that the template parameter was removed, so it's no longer possible to use `qreal` resp. `float`. That's a real pity...

Do you see any chance to revert this change so the library gets useful again for platforms with single-precision FPU?

Thanks!

**Comment by Bl4ckb0ne** [comment]
Hello, I made a few breaking changes for v2, I will put back the template argument to accept only floating points. I'll notify you when it's done.

Is this the only blocker for you?

**Comment by ubruhin** [comment]
> I made a few breaking changes for v2, I will put back the template argument to accept only floating points. I'll notify you when it's done.

Awesome! Do you already have a rough idea when it will be available - days, weeks or months? Do you need any help to get it finished soon?

> Is this the only blocker for you?

Yes so far that's the only blocker. I have an additional critical issue when multiple points are located (almost) on a straight line, then no edges are added. But I don't fully understand the problem yet, so I can't provide any details (maybe it's only a problem in my application, not in this library). But maybe this problem sounds familiar to you? :smiley:

**Comment by Bl4ckb0ne** [comment]
Im almost done with the patch, just a few things to fix. I haven't done any C++ in a while.

For the second point, the algorithm is trying to make triangle. So 3 points in a straight line will fail to triangulate because you can't make a triangle. I'll see what I can do.

**Comment by Bl4ckb0ne** [comment]
Should be fixed in [2.1](https://github.com/Bl4ckb0ne/delaunay-triangulation/tree/2.1).

**Comment by ubruhin** [comment]
> Should be fixed in 2.1.

That was fast, thanks! :smiley: 

I quickly tried to integrate the new version into my application. Now there are many compile errors when using C++11. After quick&dirty fixing them, it compiled successful, but my application behaved buggy regarding the feature which uses this library - but I could not yet determine if it's a problem on my side (since the library API has changed, I also had to update some of my code). I'll investigate this issue now...

Btw, is there any documentation how to get tests and the example built? I understand that dependencies are needed, but I have no idea how to get them installed in a way which allows meson to detect it :(

> For the second point, the algorithm is trying to make triangle. So 3 points in a straight line will fail to triangulate because you can't make a triangle. I'll see what I can do.

Yeah I agree that three points on a straight line do not make sense to build triangles. But the problem is that if there are hundreds or thousands of points, and just a few of them are on a straight line, high effort is needed to detect the missing edges after running the triangulation and handle them somehow separately. I already tried to detect such points *before* running the triangulation, but it seems to be difficult to know which points will be handled properly by this library, and which won't (I mean, what *exactly* is a "straight line", especially when using floating point coordinates?)...

Maybe I'm not a typical user of such a library, but unfortunately in my PCB development application it could cost users real money if edges are missing, because manufactured PCBs have some copper traces missing :wink: So for us, missing edges are a serious problem :(

**Comment by Bl4ckb0ne** [comment]
Since 2.0 the project is using c++17, is that an issue with your code?

The only two dependencies are catch2 for the tests and sfml for the example. Which disto are you using?

Amd regarding the 3 points in almost a straight line, could you open another issue with a [mcve](https://stackoverflow.com/help/minimal-reproducible-example) please.

**Comment by ubruhin** [comment]
> Since 2.0 the project is using c++17, is that an issue with your code?

Yeah we compile LibrePCB with C++11 because IMHO that's currently the most portable C++ standard. Most of the available libraries are compatible with C++11, and most platforms provide a toolchain which supports C++11. Thus I think it is the best option to develop applications using C++11 too.

If I make this library compilable with C++11 again, would you accept a PR? It seems that only a few small changes are needed to get C++11 compatibility back.

> The only two dependencies are catch2 for the tests and sfml for the example. Which disto are you using?

Currently I use Linux Mint 18 (Ubuntu 16.04 based). But I also tried it in a Ubuntu 19.10 Docker container - I got SFML working, but I couldn't find any "catch2" library. I installed the Apt package "catch", but that does not seem to be the correct library...

> And regarding the 3 points in almost a straight line, could you open another issue with a mcve please.

Sure, will do! :+1:

**Comment by Bl4ckb0ne** [comment]
> If I make this library compilable with C++11 again, would you accept a PR?
Sure, I think I only use C++17 for some syntax shortcuts, It should take a few minutes to do it.

> OK, I found a way to manually install the Catch2 library.
I could add a download step in meson in case the header is not found on the system.

**Comment by ubruhin** [comment]
> I could add a download step in meson in case the header is not found on the system.

That would be nice! :+1:

> Is everything ok with the floating-point template? If so, can I close the issue?

Sure, this issue can be closed.
