### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by hduonggithub** [Bl4ckb0ne/delaunay-triangulation#3]
Hi

I am developing c++ in windows and compiling your code by g++ in minGW. I have also downloaded SFML and placed inside the folder of the code.  But I got an error say, 

fatal error: SFML/Graphics.hpp: No such file or directory
 #include < SFML/Graphics.hpp >
"compilation terminated."
"make: *** [main.o] Error 1"

I think I did not know where I should set the path to this header file. Do you know any idea? 

May I compile the code in Visual Studio in windows?

One more question is that how long does it take to triangulate for 1 million points?

Thank you for your help in advance.

Hieu

**Comment by Bl4ckb0ne** [comment]
Hi,

I never tested the code on Windows, but I don't think that's how you install the sfml. Check [http://www.sfml-dev.org/tutorials/2.3/start-cb.php](this guide) to install it with code blocks.

And I don't know the time for 1 million points. But the graphic display is not really optimized, so it should be a lot quicker.
