### ISSUE TITLE
Performance of the library

### ISSUE THREAD

**Issue by Edward-Yung** [Bl4ckb0ne/delaunay-triangulation#5]
I try to embed it into some algorithms, but the experimental time/#points result of this library is ~O(n^3), (e.g: ~30s for ~2000 pts), which is not fast enough compared to others . But this library is good as no dependency at all.

**Comment by Bl4ckb0ne** [comment]
Hi,

I know that the code is not optimized. But I can't really work on it this time.

Although, this implementation is from the [Bowyer-Watson](https://en.m.wikipedia.org/wiki/Bowyer–Watson_algorithm) algorithm. The [Delaunay](https://en.m.wikipedia.org/wiki/Delaunay_triangulation) should be more efficient, but I didn't try to implement it.

If you want to do something about the optimization, I will be happy to review your PR.

**Comment by Edward-Yung** [comment]
Cool,  I am reading fade2d and qhull's page.  Will do a pr if the code can be optimized. :)

**Comment by Bl4ckb0ne** [comment]
Awesome! Thanks!
