### ISSUE TITLE
Allow for doubles instead of just floats

### ISSUE THREAD

**Issue by abetusk** [Bl4ckb0ne/delaunay-triangulation#8]
It would be nice to have support for `doubles` instead of just `floats`.

I'm not sure what the form should be (should it be an extra class where you can give the type you want when you create it?  Should the original class definition be changed so that you specify a type?).  I'm using this for a project of mine and I ran into round-off issues with using floats, so I changed all occurrences to doubles.

**Comment by Bl4ckb0ne** [comment]
I think it would be possible using the templates, but I'm really occupied these times so I don't think I'll do it soon, but I would keep that in mind

**Comment by abetusk** [comment]
I don't mind doing this but I don't have an idea of what this looks like.  I'm also not that familiar with C++ conventions as much as  should be.  Should the library be wrapped in some sort of namespace?  For each of the main classes (Triangle, Edge, Delaunay), should there be an extra one where you can provide the type?  Should the main classes be changed and not worry about "backwards compatibility"?
